### PR TITLE
Update Microsite with additional resources

### PR DESCRIPTION
**Pull request by baldram**
Finding exciting content might be helpful for newcomers until the microsite gets out of the TODO phase.

### CODE REVIEW

**Review by sideeffffect — APPROVED** [review]
Nice! Thanks a lot :smiley:

**Comment by baldram** [comment]
Right now, the master is broken, so obviously pipeline failed also here. 
Shall I wait and sync with master when fixed to get pipeline green here as well?

**Comment by sideeffffect** [comment]
@adamgfraser any comments? If not, I think we can happily merge this :slightly_smiling_face:

**Comment by adamgfraser** [comment]
Yes this looks great!

**Pull request merged**
