### PR TITLE
Added contains method to Traversable

### PR DESCRIPTION
**Pull request by Michaelt293**
As the title says :)

### CODE REVIEW

**Comment by adamgfraser** [comment]
@Michaelt293 Looks great!

@mijicd or @softinio Any idea what is going on with CI here?

**Comment by mijicd** [comment]
@adamgfraser looks like the sbtx problem. Fixing it in a sec!

**Comment by adamgfraser** [comment]
@mijicd Awesome! Thank you! 🙏

**Comment by mijicd** [comment]
@Michaelt293 @adamgfraser sync with master should fix it!

**Comment by Michaelt293** [comment]
I have merged the latest master into the branch.

**Pull request merged**
