### PR TITLE
Small improvements to the *Both and *Either hierarchies

### PR DESCRIPTION
**Pull request by sideeffffect**
Add instances for `Hash`.
Condense the instances for `Equal`.

### CODE REVIEW

**Comment by sideeffffect** [comment]
@adamgfraser could you please restart that dead build, please? :pray:

**Comment by adamgfraser** [comment]
@sideeffffect Yep!

**Comment by sideeffffect** [comment]
And we're green :tada:

**Review by adamgfraser — APPROVED** [review]
Looks great!

**Pull request merged**
