### PR TITLE
Attempt To Resolve CI Flakiness

### PR DESCRIPTION
**Pull request by adamgfraser**

### CODE REVIEW

**Comment by sideeffffect** [comment]
Wow. I would guess that it would be `val`s, not `lazy val`s that are causing issues. So I would be trying adding more `lazy`, but I don't really know what I'm doing :smile: 

But apparently we still get 2 stalled builds :disappointed:

**Review by sideeffffect — APPROVED** [review]
Feel free to go ahead with this experiment :crossed_fingers:

**Comment by adamgfraser** [comment]
Well these failures indicate that my hypothesis was clearly wrong. I'm not sure what the cause is but I can tell you that I have not seen this behavior in any other ZIO ecosystem project so I think it is something we are doing and not ZIO or Github Actions.

**Comment by sideeffffect** [comment]
Or maybe we're pushing _something_ to the point it sometimes break. _something_ could be Scala's `lazy val`s, ZIO, ... :shrug: I really have no idea :smile_cat:

**Pull request closed without merging**
