### PR TITLE
add fromOptions constructor for the These data type

### PR DESCRIPTION
**Pull request by yisraelU**
I came across this use case , where I had 2 options and found it easier to work with an option of These .
Does this make sense ?

### CODE REVIEW

**Review by sideeffffect — CHANGES_REQUESTED** [review]
What a nice contribution! :heart: 
Please run `sbt fix` to format the codebase so that the build is green -- it's not formatted properly
https://github.com/zio/zio-prelude/runs/4328333237?check_suite_focus=true
After that, we can go ahead and merge it, right @adamgfraser ?

**Review by sideeffffect — APPROVED** [review]

**Comment by sideeffffect** [comment]
Thanks again Yisrael :+1:

**Comment by yisraelU** [comment]
Thank you, hope to contribute some more.

**Comment by sideeffffect** [comment]
Looking forward to it! :muscle:

**Pull request merged**
