### PR TITLE
Update Contributing.md (replace fmt with fix)

### PR DESCRIPTION
**Pull request by phderome**
as headline says

See https://github.com/zio/zio-prelude/pull/584#issuecomment-803642226

### CODE REVIEW

**Comment by adamgfraser** [comment]
Love aligning this but would actually go the other way and just rename `fix` to `fmt` so we have the same command for users who are contributing to both ZIO and ZIO Prelude.

**Comment by phderome** [comment]
> Love aligning this but would actually go the other way and just rename `fix` to `fmt` so we have the same command for users who are contributing to both ZIO and ZIO Prelude.

Now I "get" it.

**Review by sideeffffect — APPROVED** [review]
`fix` is actually the correct command. It works on both ZIO and ZIO Prelude. It runs both Scalafix and Scalafmt to ensure all what can be automatically fixed gets fixed :wink:

**Comment by phderome** [comment]
closing until there is absolute clarity. Perhaps it's the ZIO project that needs updating.

**Pull request closed without merging**
