### PR TITLE
Implement Max and Min Extension Methods

### PR DESCRIPTION
**Pull request by adamgfraser**
Available on any data type for which an `Ord` is defined.

### CODE REVIEW

**Review by sideeffffect — APPROVED** [review]
Nice addition :+1: 
Do you Adam think it would make sense to have `min`/`max` also on `Ord` proper (i.e. no only as "extension methods")? Then we could re-use the implementation in the extension methods...

**Comment by sideeffffect** [comment]
All green :green_circle:

**Comment by adamgfraser** [comment]
@sideeffffect Yes I think that is a good idea. Will add.

**Review by sideeffffect — APPROVED** [review]

**Comment by sideeffffect** [comment]
All green :green_circle:

**Pull request merged**
