### PR TITLE
Clean Up Docs

### PR DESCRIPTION
**Pull request by khajavi**
- Use the categorized sidebar
- Use SEO-friendly URLs
- Update the home page

### CODE REVIEW

**Review by adamgfraser — APPROVED** [review]

**Review by adamgfraser — APPROVED** [review]

**Comment by sideeffffect** [comment]
Oh, so now we have the documentation of all the ZIO libs on one site. Nice! :+1: 

But I've noticed that the API reference link, even on ZIO Prelude, points to ZIO itself on javadoc.io, instead of to

https://zio.github.io/zio-prelude/api/zio/prelude/

image

Is there a plan to remedy that?

**Comment by adamgfraser** [comment]
I think I would expect the bottom navigation bar to go to ZIO itself since all the content there is "global" to ZIO (the stars for the ZIO project, etc...) but it would be good to link to the Scaladoc for the individual projects somewhere.

Copying @khajavi.

**Comment by sideeffffect** [comment]
The best thing would be to have just one single API reference for all official ZIO libraries (including ZIO proper, ZIO Prelude, and all the others). Of course, that would have to be hosted by us, javadoc.io won't help us here.

**Comment by khajavi** [comment]
@sideeffffect Yes, I agree that having a single API reference for all official libraries is necessary. However, I have not yet started on that. If you have any suggestions, please share them with me.

**Pull request merged**
