### PR TITLE
Mermaid rendered by Docusaurus

### PR DESCRIPTION
**Pull request by sideeffffect**
Docusaurus 2.2.x has introduced native support for Mermaid which we use for Abstractions diagrams.
This will allow us to simplify the code for the diagrams significantly.

https://docusaurus.io/blog/releases/2.2
https://docusaurus.io/docs/markdown-features/diagrams

@khajavi can you please upgrade to the newest version of Docusaurus? :pray:

### CODE REVIEW

**Comment by lemastero** [comment]
Hi, I was playing around with [built-in support for mermaid](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/) diagrams - [here is an example](https://github.com/lemastero/scala_typeclassopedia/blob/master/README.MD).
I am not sure if this will be properly rendered [web page](https://zio.github.io/zio-prelude/docs/overview/overview_diagrams).

**Comment by sideeffffect** [comment]
It will, I tested it with Docusaurus 2.2.0 :wink:

**Comment by khajavi** [comment]
> Docusaurus 2.2.x has introduced native support for Mermaid which we use for Abstractions diagrams. This will allow us to simplify the code for the diagrams significantly.
> 
> https://docusaurus.io/blog/releases/2.2 https://docusaurus.io/docs/markdown-features/diagrams
> 
> @khajavi can you please upgrade to the newest version of Docusaurus? pray

Yes for sure! I'll notify you whenever I managed to do that.

**Review by khajavi — DISMISSED** [review]

**Review by adamgfraser — DISMISSED** [review]

**Review by adamgfraser — APPROVED** [review]

**Comment by sideeffffect** [comment]
@khajavi how can I can't see the effect of this PR on https://zio.dev/zio-prelude/ ?

**Comment by sideeffffect** [comment]
@khajavi :pleading_face:

**Comment by khajavi** [comment]
Excuse me for my late reply. It seems I didn't notify your previous message.
I'll check that shortly.

**Comment by khajavi** [comment]
@sideeffffect 
zio.dev is based on the latest documentation package of zio-prelude:
https://github.com/zio/zio/blob/16138b37e3b7bbeaa2fc44b5ce70f04aed1392ba/website/package.json#L56
https://www.npmjs.com/package/@zio.dev/zio-prelude
After the next release of zio-prelude, we need to update the `website/package.json` file of github.com/zio/zio repo.

**Comment by sideeffffect** [comment]
I see, that makes sense, thanks.

**Pull request merged**
