### PR TITLE
Add Assertion Variants

### PR DESCRIPTION
**Pull request by adamgfraser**

### CODE REVIEW

**Comment by sideeffffect** [comment]
Scala 3 doesn't like it :disappointed: ... Maybe a workaround, like renaming to `isSuccessVAnything` is needed? :shrug:

**Comment by adamgfraser** [comment]
Yes. Let's see if there is anything we can do with the smart types first since similar variants work in ZIO Test without the smart types. But if not we can always fall back on renaming.

**Comment by adamgfraser** [comment]
@kitlangton Can you take a look at this when you get the chance?

**Comment by sideeffffect** [comment]
This may be worth resurrecting :thinking:  /cc @jdegoes

**Pull request closed without merging**
