### PR TITLE
Add ZNonEmptySet

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Review by adamgfraser — CHANGES_REQUESTED** [review]
There is a lot of code duplication here. We're basically reimplementing all of the `ZSet` which is going to create a maintenance issue in the future. Why don't we wrap a `ZSet` and just maintain the invariant that it is non-empty like we did for set?

**Comment by sideeffffect** [comment]
good point! I'll make the changes

**Review by adamgfraser — APPROVED** [review]

**Comment by adamgfraser** [comment]
Good to merge when conflicts are resolved!

**Comment by sideeffffect** [comment]
Conflicts resolved, build green, ready to be merged :rocket:

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
