### PR TITLE
Refined Refinement

### PR DESCRIPTION
**Pull request by kitlangton**
This PR collapses `Newtype` and `NewtypeSmart` into a single representation that allows for compile-time validation of values. The biggest improvement is that this allows for a *near* identical syntax between the Scala 2 and 3 versions:

*Scala 2*

```scala
import zio.prelude._
import zio.prelude.Refinement._

type Age = Age.Type
object Age extends Newtype[Int] {
  def refinement = refine(greaterThan(0) && lessThan(120))
}
```

*Scala 3*

```scala
import zio.prelude.*
import zio.prelude.Refinement.*

type Age = Age.Type
object Age extends Newtype[Int] {
  override inline def refinement = greaterThan(0) && lessThan(120)
}
```

Remaining work:

- [x] Get everything to work on Scala 2 and 3
- [x] Create a shared compile-time spec, abstracting Newtype definitions into VersionSpecific traits
- [x] Abstract `newtypes.Natural` into VersionSpecific trait
- [x] Add doc comments
- [x] Add docs
- [x] Add examples
- [x] Deprecate `Smart` variants, document how to migrate for release notes

### CODE REVIEW

**Comment by jdegoes** [comment]
@kitlangton Love it! What a huge improvement to usability this is. ❤️

**Comment by kitlangton** [comment]
Everything finally passes. That took a while. `2.11.12` is extra sensitive.

**Review by adamgfraser — APPROVED** [review]
Fantastic!

**Comment by adamgfraser** [comment]
@kitlangton Is this ready to go?

**Pull request merged**
