### PR TITLE
#375 'some*' family of methods for ZPure

### PR DESCRIPTION
**Pull request by arnoldlacko**
Related to #375

### CODE REVIEW

**Review by sideeffffect — APPROVED** [review]
Awesome job @arnoldlacko :tada: Unless @adamgfraser has anything to add, I think we can merge this :+1:

**Comment by arnoldlacko** [comment]
> Awesome job @arnoldlacko  Unless @adamgfraser has anything to add, I think we can merge this

Thank you @sideeffffect , sorry about the late update, I had to amend due to incorrect committer details.

**Review by sideeffffect — DISMISSED** [review]
Cool :+1:

**Comment by sideeffffect** [comment]
@arnoldlacko could you please fix the merge conflicts? :pray:

**Comment by adamgfraser** [comment]
Looks great! Unfortunately we seem to have managed to create more merge conflicts in the meantime but good to go once those are resolved!

**Review by adamgfraser — APPROVED** [review]

**Review by sideeffffect — APPROVED** [review]

**Comment by sideeffffect** [comment]
Thanks again!

**Pull request merged**
