### PR TITLE
[Scala3] Fix: `SubtypeCustom[A]` should behave like subtype of `A`

### PR DESCRIPTION
**Pull request by guizmaii**

### CODE REVIEW

**Review by sideeffffect — APPROVED** [review]

**Comment by guizmaii** [comment]
@sideeffffect Thanks 🙏

Do you think you could release a new version, maybe?

**Comment by sideeffffect** [comment]
Than _you_ for the fix :wink: 
https://github.com/zio/zio-prelude/releases/tag/v1.0.0-RC27

**Comment by sideeffffect** [comment]
@jdegoes could you please make @guizmaii a co-maintainer of the repository? He's an active user and contributor and it'd help to have somebody else here too :pray:

**Comment by guizmaii** [comment]
@sideeffffect Thanks for your trust ❤️

**Pull request merged**
