### PR TITLE
provide ZValidation.flatten

### PR DESCRIPTION
**Pull request by phderome**

### CODE REVIEW

**Review by adamgfraser — APPROVED** [review]
Looks great! Thanks for adding!

**Review by sideeffffect — DISMISSED** [review]
Awesome, thank you!

**Comment by adamgfraser** [comment]
@phderome Can you format?

**Comment by sideeffffect** [comment]
@phderome you may want to run `fix` before submitting a PR to make sure `lint` won't fail :wink:

**Comment by phderome** [comment]
> @phderome you may want to run `fix` before submitting a PR to make sure `lint` won't fail 😉

Will do. Consider adding that to https://zio.github.io/zio-prelude/docs/about/about_contributing as I didn't see it there being mentioned.

**Comment by adamgfraser** [comment]
@phderome I think we should align the commands with the ones in ZIO. The contributor's guide actually does mention it here but it is the wrong command.

image

**Comment by sideeffffect** [comment]
`fix` works on both ZIO and ZIO Prelude. It runs _both_ Scalafix and Scalafmt to ensure all what can be automatically fixed gets fixed :wink:

**Comment by adamgfraser** [comment]
Sorry, I'm thinking of `prepare`. I think we have that on ZIO but not on ZIO Prelude.

**Comment by adamgfraser** [comment]
https://github.com/zio/zio/blob/9a199aff8bd0b649f1573a4d2097f062795d8ff9/build.sbt#L27

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
