### PR TITLE
Build ZEnvironment Into ZPure

### PR DESCRIPTION
**Pull request by adamgfraser**
Builds `ZEnvironment` into `ZPure` the same way it is in ZIO in ZIO 2.0. This will provide consistency between the use of the environment between `ZIO` and `ZPure`.

### CODE REVIEW

**Review by sideeffffect — CHANGES_REQUESTED** [review]
:heart: 
Looks great!
We just need to touch up the docs as well
```scala
info: Compiling 40 files to /home/runner/work/zio-prelude/zio-prelude/zio-prelude-docs/target/mdoc
error: index.md:216:3: polymorphic expression cannot be instantiated to expected type;
 found   : [S, R]zio.prelude.fx.ZPure[Nothing,S,S,R,Nothing,zio.ZEnvironment[R]]
 required: zio.prelude.fx.ZPure[Nothing,Unit,Unit,App0.this.AccountEnvironment,Nothing,App0.this.AccountEnvironment]
  ZPure.environment
  ^^^^^^^^^^^^^^^^^
error: index.md:225:3: value access is not a member of object zio.prelude.fx.ZPure
  ZPure.access(_.interestRate)
  ^^^^^^^^^^^^
error: index.md:235:3: value accessZPure is not a member of object zio.prelude.fx.ZPure
  ZPure.accessZPure(r => computeSimpleInterest(balance, days, r.interestRate))
  ^^^^^^^^^^^^^^^^^
error: index.md:242:3: value provide is not a member of zio.prelude.fx.ZPure[Nothing,Unit,Unit,App0.this.AccountEnvironment,Nothing,Double]
  accruedInterest(100000, 30).provide(AccountEnvironment(0.05))
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by adamgfraser** [comment]
@sideeffffect Should be ready to go now.

**Review by sideeffffect — APPROVED** [review]
Awesome!

**Comment by jdegoes** [comment]
Perfect!

**Pull request merged**
