### PR TITLE
Document the Type Class hierarchies with chart: Equal

### PR DESCRIPTION
**Pull request by sideeffffect**
fixes https://github.com/zio/zio-prelude/issues/322

Rendered: https://github.com/sideeffffect/zio-prelude/blob/322-visual-equal/docs/overview/diagrams.md

### CODE REVIEW

**Comment by adamgfraser** [comment]
@sideeffffect Love the idea here! However, I get a `Mermaid syntax error` message when I try to view it right now.

**Comment by sideeffffect** [comment]
Yeah, me too. Still needs more work :muscle: But that will have to wait till tomorrow :sleeping:

**Comment by sideeffffect** [comment]
OK!
I think I figured out how we can do this. Mermaid class diagram come with their set of compromises, but I think this will do, until we figure out something better.

**Comment by sideeffffect** [comment]
ready to be merged :muscle:

**Review by adamgfraser — APPROVED** [review]
Great!

**Pull request merged**
