### PR TITLE
Port ZIO#reject methods into ZPure

### PR DESCRIPTION
**Pull request by landlockedsurfer**
Hi!
Here's my pull request to port ZIO's reject and rejectM methods including some tests.
Hope I did not mess up the type signature! 🤞

### CODE REVIEW

**Review by sideeffffect — CHANGES_REQUESTED** [review]
Hello @landlockedsurfer , thanks for the contribution!
You'll have to run `sbt fix` to make the linter happy :smiley:

**Comment by landlockedsurfer** [comment]
I had used `scalafmt` instead... but just run `sbt fix`ed it and pushed the changes.

**Review by sideeffffect — CHANGES_REQUESTED** [review]
Great! I think your changed look fine.
Once you'll fix the Scala 2.13 issue with `fail`, we could merge this :+1: 
https://app.circleci.com/pipelines/github/zio/zio-prelude/940/workflows/a3c66ec8-b60f-48c9-9d67-ff7cb7ad80d6/jobs/6019

**Review by sideeffffect — CHANGES_REQUESTED** [review]
And now it's Dotty that's complaining :smile:
Perhaps `fail(_)` would help?

But first, please merge recent `master` into your branch, so that CircleCI builds for Scala Native.

Thank you for the patience with all these nuisances :smile_cat:

**Comment by sideeffffect** [comment]
@landlockedsurfer If you'd like more interactive help with this, just let me know -- we could do it via Discord or Zoom :wink:

**Review by sideeffffect — APPROVED** [review]
Awesome, thanks for contributing to ZIO Prelude. Once builds are green, and they should, I believe, we can merge :+1:

**Comment by landlockedsurfer** [comment]
Great! 🎉😀  Thanks for your help also!

**Pull request merged**
