### PR TITLE
Try automatic-pull-request-review instead

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Comment by sideeffffect** [comment]
@adamgfraser @mijicd 
CircleCI job died of `Too long with no output`, could somebody please restart it? :pray: 
(it died during compilation, so it definitely wasn't because of a bug in ZIO runtime, btw)

**Comment by adamgfraser** [comment]
@sideeffffect Done.

**Comment by sideeffffect** [comment]
hmm... it still seems to be dead.

**Comment by adamgfraser** [comment]
Just tried again.

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
