### PR TITLE
Port ZIO#left methods into ZPure

### PR DESCRIPTION
**Pull request by zach-albia**
#375

### CODE REVIEW

**Review by adamgfraser — DISMISSED** [review]
Looks great!

**Comment by zach-albia** [comment]
@adamgfraser It looks like test_212_jdk8_js has timed out again, unfortunately 😕

**Comment by zach-albia** [comment]
It looks to me like whatever is causing the build in #416 to fail is the same for this one.

**Review by sideeffffect — APPROVED** [review]
Nice job, @zach-albia ! I've restarted the build, let's hope it passes this time :crossed_fingers:

**Comment by sideeffffect** [comment]
I see there's a conflict. Could you please resolve it? :pray:

**Comment by zach-albia** [comment]
The CI test failure is reporting "Too long with no output (exceeded 10m0s): context deadline exceeded". Could someone please try running both **test_212_jdk8_js** and **test_213_jdk8_js** again?

**Comment by sideeffffect** [comment]
We sometimes get spurious errors like this. I've restated those builds :wink:

**Review by sideeffffect — APPROVED** [review]
Great job! We're merging :tada:

**Pull request merged**
