### PR TITLE
Sketch of NewtypeSmartF and SubtypeSmartF

### PR DESCRIPTION
**Pull request by sideeffffect**
fixes https://github.com/zio/zio-prelude/issues/483

Is this what you had in mind, @jdegoes ?

On a second thought, shouldn't these be called rather `NewtypeSmartK` and `SubtypeSmartK`?

### CODE REVIEW

**Review by adamgfraser — CHANGES_REQUESTED** [review]
I think this looks good. Can we add some tests so we can see the functionality in action?

**Comment by sideeffffect** [comment]
Hi, this should be ready for merging :wink:

**Review by adamgfraser — APPROVED** [review]
Awesome!

**Comment by sideeffffect** [comment]
Btw, are you guys @adamgfraser @jdegoes comfortable with the name `NewtypeSmartF`, `SubtypeSmartF` (so not `NewtypeSmartK` and `SubtypeSmartK`) and `AssertionK`?

**Comment by adamgfraser** [comment]
I think we use `F` elsewhere so we should stick with that,

**Comment by sideeffffect** [comment]
Should I rename `AssertionK` to `AssertionF`? What is the distinction between `F` and `K`? (AFAIK, `XyzK` communicates that it is like `Xyz`, but on a "kind level", like `Function` is about `A => B` and `FunctionK` is about `A[_] => B[_]`) :thinking:

**Comment by adamgfraser** [comment]
I thought we were just kind of using `F` instead of `K` so I think we should align everything around that.

**Pull request merged**
