### PR TITLE
Up out CI game

### PR DESCRIPTION
**Pull request by sideeffffect**
* use Renovate to maintain versions in GitHub Actions
 * manually managing each CI sub-step is unsustainable, now we have a step `ci` which aggregates all the necessary steps and which other tools can reference (e.g. GitHub or Mergify)
 * single source of truths for versions
   * Scala versions are read from `.github/workflows/ci.yml`
   * in `.github/workflows/ci.yml`, versions are not duplicated
 * better policy for Release Drafter, with better labeling support (taken from Release Drafter itself)

### CODE REVIEW

**Comment by sideeffffect** [comment]
This is ready to be reviewed/merged. Could you please remove the requirements on the individual tests? Requiring `ci` is enough now :wink: 
/cc @adamgfraser @mijicd

**Review by mijicd — APPROVED** [review]
I am fine with the changes here, however, this is solving a non existent problem for the price of making maintenance more difficult (inconsistent with other repositories). If this goes in here, it must go everywhere else.

**Comment by sideeffffect** [comment]
> If this goes in here, it must go everywhere else.

I would be happy to contribute such changes in other ZIO projects. (I already have an analogous PR for ZIO itself up my sleeve :wink: )

**Review by mijicd — APPROVED** [review]

**Comment by sideeffffect** [comment]
@mijicd Could you please adjust the Required builds? :pray:

**Pull request merged**
