### PR TITLE
add Zivariant

### LINKED ISSUE #291: add Trifunctor
Adding `Divariant` instances (issue #290) to types with 3 params leads to duplications:
1. two different dimap that does different things
   * map over input and error
   * map over input and output
2. two contramap defined the same way
```scala
implicit def ZIODivariant[E]: Divariant[({ type lambda[-R, +A] = ZIO[R, E, A] })#lambda] =
  new Divariant[({ type lambda[-R, +A] = ZIO[R, E, A] })#lambda] {

    override def leftMap[R, A, RR](f: RR => R): ZIO[R, E, A] => ZIO[RR, E, A] =
      zio => zio.provideSome(f)

    override def rightContramap[A, B, C](g: B => C): ZIO[A, E, B] => ZIO[A, E, C] =
      _.map(g)
  }

implicit def FailedZIODivariant[A]: Divariant[({ type lambda[-R, +E] = ZIO[R, E, A] })#lambda] =
  new Divariant[({ type lambda[-R, +E] = ZIO[R, E, A] })#lambda] {
    override def leftMap[R, E, RR](f: RR => R): ZIO[R, E, A] => ZIO[RR, E, A] =
      zio => zio.provideSome(f)

    override def rightContramap[R, E, EE](f: E => EE): ZIO[R, E, A] => ZIO[R, EE, A] =
      _.mapError(f)
  }
```
3. the same implementation of contramap in `Convtravariant`
```scala
implicit def ZIOContravariant[E, A]: Contravariant[({ type lambda[-x] = ZIO[x, E, A] })#lambda] =
  new Contravariant[({ type lambda[-x] = ZIO[x, E, A] })#lambda] {
    def contramap[R, R0](f: R0 => R): ZIO[R, E, A] => ZIO[R0, E, A] =
      zio => zio.provideSome(f)
  }
```
4. both version of map defined in `Covariant` (for X and Failed[X])
```scala
implicit def ZIOCovariant[R, E]: Covariant[({ type lambda[+a] = ZIO[R, E, a] })#lambda] =
  new Covariant[({ type lambda[+a] = ZIO[R, E, a] })#lambda] {
    def map[A, B](f: A => B): ZIO[R, E, A] => ZIO[R, E, B] = { zio =>
      zio.map(f)
    }
  }

implicit def ZIOFailureCovariant[R, A]: Covariant[({ type lambda[+e] = Failure[ZIO[R, e, A]] })#lambda] =
  new Covariant[({ type lambda[+e] = Failure[ZIO[R, e, A]] })#lambda] {
    def map[E, E1](f: E => E1): Failure[ZIO[R, E, A]] => Failure[ZIO[R, E1, A]] = { zio =>
      Failure.wrap(Failure.unwrap(zio).mapError(f))
    }
  }
```

5. If PR #279 will enter then both map's defined in Bicovariant (problem raised by @adamgfraser [here])(https://github.com/zio/zio-prelude/pull/279#issuecomment-693697605) 
```scala
implicit def ZIOFailureCovariant[R, A]: Covariant[({ type lambda[+e] = Failure[ZIO[R, e, A]] })#lambda] =
  new Covariant[({ type lambda[+e] = Failure[ZIO[R, e, A]] })#lambda] {
    def map[E, E1](f: E => E1): Failure[ZIO[R, E, A]] => Failure[ZIO[R, E1, A]] = { zio =>
      Failure.wrap(Failure.unwrap(zio).mapError(f))
    }
  }
```

A possible solution would be to use type class: [Trifuctor[-R,+E,+A]](https://github.com/lemastero/Triglav/blob/master/src/main/scala/Triglav/face3/Trifunctor.scala)

```scala
trait Trifunctor[F[-_,+_,+_]] {

  def timap[E,A,R,EE,AA,RR](fa: F[E,A,R])(
    f: EE => E,
    g: A => AA,
    h: R => RR): F[EE,AA,RR]

 // derived
 def contramap[E, A, R, EE](fa: F[E, A, R])(f: EE => E): F[EE, A, R] = timap(fa)(f, identity[A], identity[R])
 def mapLeft[E, A, R, AA](fa: F[E, A, R])(g: A => AA): F[E, AA, R] = timap(fa)(identity[E], g, identity[R])
 def map[E, A, R, RR](fa: F[E, A, R])(h: R => RR): F[E, A, RR] = timap(fa)(identity[E], identity[A], h)
 def bimap[E, A, R, AA, RR](fa: F[E, A, R])(g: A => AA, h: R => RR): F[E, AA, RR] = timap(fa)(identity[E], g, h)
 def dimapLeft[E, A, R, EE, AA](fa: F[E, A, R])(f: EE => E, g: A => AA): F[EE, AA, R] = timap(fa)(f, g, identity[R])
 def dimap[E, A, R, EE, RR](fa: F[E, A, R])(f: EE => E, h: R => RR): F[EE, A, RR] = timap(fa)(f, identity[A], h)
}
```
[I tried to do it here](https://github.com/lemastero/Triglav/blob/master/src/main/scala/Triglav/instances/TrifunctorInstancesZIO.scala). It can handle:
```scala
ZIO[-R, +E, +A]
ZLayer[-RIn, +E, +ROut]
ZManaged[-R, +E, +A]
ZStream[-R, +E, +O]
ZSTM[-R, +E, +A]
```

It does have well-defined laws (functor laws on 2 params and contravariant functor laws on the first).

Looks a bit like `ZIOContextual` in #164

### PR DESCRIPTION
**Pull request by lemastero**
Fix #291 add Zivariant abstraction

### CODE REVIEW

**Comment by adamgfraser** [comment]
Maybe `Trivariant`? Though there is more that one way you could arrange variance for three type parameters and everything is either covariant or contravariant so I don't know if that is great either.

Have you had any success implementing the less polymorphic typeclasses in terms of this?

**Comment by lemastero** [comment]
> Maybe Trivariant?
@adamgfraser I started with a Trivariant name - 3 type parameters - seems like a good choice.

I changed the name to Zivariant because:
* There is a hierarchy in Haskell ([tweet by Iceland_jack
](https://twitter.com/Iceland_jack/status/1303720199879786498), [origami library](https://hackage.haskell.org/package/origami/docs/Data-Origami-Internal-Trifunctor.html), [Bartosz Milewski blog post](https://bartoszmilewski.com/2015/02/03/functoriality/)):
F[+_] - Functor
F[+_,+_] - Bifunctor
F[+_,+_,+_] - Trifunctor
so we should avoid Trifunctor name for [-_,+_,+_]
* The most common shape with 3 parameters is [-_,+_,+_], all instances in zio start from Z: ZIO, ZManaged, ZLayer, ZStream, ZSTM - so Zivariant seems a good fit
* [-_,+_,+_] is not the only shape. There are at least 2 occurrences of [-_,-_,+_] (`Schedule[-Env, -In, +Out]`, `Function2[-T1,-T2, +R]`). Using Trivariant would suggest "the only" shape with 3 type params. I would call all shapes with 3 type parameters: [-_,+_,+_], [-_,+_,+_], [+_,+_,+_], ... as trivariant.

But I am happy with Trivariant name as well if it seems more reasonable to you :)

**Comment by lemastero** [comment]
> Have you had any success implementing the less polymorphic typeclasses in terms of this?

I tried using asInstanceOf for instances - it compiles but I got runtime excaptions:
```scala
[info] - CovariantSpec
[info]   - laws
[info]     - tuple2
[info]       Fiber failed.
[info]       An unchecked error was produced.
[info]       java.lang.ClassCastException: zio.prelude.Bicovariant$$anon$2 cannot be cast to zio.prelude.Covariant
[info]       	at zio.prelude.Covariant$.Tuple2Covariant(Covariant.scala:659)
[info]       	at zio.prelude.CovariantSpec$.$anonfun$spec$6(CovariantSpec.scala:16)
[info]       	at zio.ZIO$.$anonfun$effectSuspendTotal$1(ZIO.scala:2593)
[info]       	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:581)
[info]       	at zio.internal.FiberContext.$anonfun$fork$15(FiberContext.scala:770)
[info]       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]       	at java.lang.Thread.run(Thread.java:748)
```
so this seems like a dead end.

So I used deriving mechanism similar as in Divariant:
```scala
  def deriveCovariant[R, E]: Covariant[({ type lambda[+A] = Z[R, E, A] })#lambda] =
    new Covariant[({ type lambda[+A] = Z[R, E, A] })#lambda] {
      def map[A, A1](f: A => A1): Z[R, E, A] => Z[R, E, A1] = self.map(f)
    }
``` 
It simplify instances for Covariant:
```scala
implicit def ZIOContravariant[E, A]: Contravariant[({ type lambda[-x] = ZIO[x, E, A] })#lambda] =
    new Contravariant[({ type lambda[-x] = ZIO[x, E, A] })#lambda] =
      Zivariant.ZioZivariant.deriveContravariant[E, A]
```
and similarly for Contravariant.

**Comment by lemastero** [comment]
@adamgfraser any chance this PR can be merged? It is an important stepping stone towards type alias encoding in #309

**Comment by adamgfraser** [comment]
@lemastero Let's do it!

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
