### PR TITLE
Fixed documentation of ZSet.fromMap

### PR DESCRIPTION
**Pull request by timgesekus**
The documentation of fromMap had no proper ending.

### CODE REVIEW

**Comment by adamgfraser** [comment]
Thanks for the fix! Can you merge upstream changes to get the fix for the CI issue and sign the CLA?

**Comment by timgesekus** [comment]
Hi,
I merged upstream and signed the CLA. But the checker isn't happy. On the details page everything seems to be  ok.

Screenshot from 2020-08-10 21-51-16

**Comment by adamgfraser** [comment]
I think you need to add the e-mail address you did your commits from to your Github profile.

**Comment by jdegoes** [comment]
Thank you!

**Pull request merged**
