### PR TITLE
Fix #1091 (@mschuwalow idea)

### LINKED ISSUE #1091: Difference of Newtype behaviour in pattern matching between RC16 and RC17
Hi,

I tried to update zio-prelude in our project, but some tests fail because the behaviour of newtypes in pattern matching has changed between RC16 and RC17.

This prints `"toto"` with RC16 but prints `"tata"` with RC17:
```scala
import zio.prelude._
import zio.prelude.Assertion._

object Id extends Subtype[Int] {
  override def assertion = assert(greaterThanOrEqualTo(0))
}
type Id = Id.Type

Id(1) match {
  case Id(1) => println("toto")
  case _     => println("tata")
}
```

I'm not sure which behaviour is correct. I'd say that the one from RC16 is the correct one

RC16: https://scastie.scala-lang.org/cvjxJq3JQ6Czy5Vg0jqE5g
RC17: https://scastie.scala-lang.org/OrlZvhDrSDmfLqzgmLgCcQ

### PR DESCRIPTION
**Pull request by guizmaii**
Fix https://github.com/zio/zio-prelude/issues/1091

Based on: https://github.com/zio/zio-prelude/pull/1092

### CODE REVIEW

**Comment by mschuwalow** [comment]
That looks promising 👍, Try with this patch for the remaining tests:

```
diff --git a/core/shared/src/main/scala-2/zio/prelude/Newtype.scala b/core/shared/src/main/scala-2/zio/prelude/Newtype.scala
index 309dd06..92841f1 100644
--- a/core/shared/src/main/scala-2/zio/prelude/Newtype.scala
+++ b/core/shared/src/main/scala-2/zio/prelude/Newtype.scala
@@ -324,7 +324,5 @@ object Newtype {
   }
 
   implicit def classTag[N <: Newtype[_]: ClassTagWrapper]: ClassTag[N#Type] =
-    new ClassTag[N#Type] {
-      def runtimeClass: Class[_] = ClassTagWrapper[N].classTag.runtimeClass
-    }
+    ClassTagWrapper[N].classTag.asInstanceOf[ClassTag[N#Type]]
 }

```

**Comment by guizmaii** [comment]
Tests are passing! You're a genius @mschuwalow! Thanks for your help! ❤️

**Comment by adamgfraser** [comment]
Can we revert the increase to the test timing please?

**Comment by guizmaii** [comment]
> Can we revert the increase to the test timing please?

@adamgfraser the tests for Scala3 are taking more than 60 minutes, that's why I did this 😕

**Comment by adamgfraser** [comment]
@guizmaii Why is this making an impact on that?

**Comment by guizmaii** [comment]
@adamgfraser I'm not sure 🤔

What I see on that PR https://github.com/zio/zio-prelude/pull/1099 for example is that the Scala3 tests take already near 60 minutes:
image

In this PR, they now take 1h03, so ~10 minutes more (which is a lot, I agree):
image

**Comment by adamgfraser** [comment]
Let's leave the CI settings as is, get this in, and we can address the test timing separately.

**Comment by guizmaii** [comment]
@adamgfraser One thing I spotted in the CI output of this PR compared to yours is that I have these tests reported as slow:
```scala
Test parSeqSpec - hashCode has taken more than 1 m to execute. If this is not expected, consider using TestAspect.timeout to timeout runaway tests for faster diagnostics.
[1501](https://github.com/zio/zio-prelude/actions/runs/4340205509/jobs/7578530671#step:10:1502)
Test parSeqSpec - laws - covariant has taken more than 1 m to execute. If this is not expected, consider using TestAspect.timeout to timeout runaway tests for faster diagnostics.
[1502](https://github.com/zio/zio-prelude/actions/runs/4340205509/jobs/7578530671#step:10:1503)
Test parSeqSpec - laws - hash has taken more than 1 m to execute. If this is not expected, consider using TestAspect.timeout to timeout runaway tests for faster diagnostics.
[1503](https://github.com/zio/zio-prelude/actions/runs/4340205509/jobs/7578530671#step:10:1504)
Test parSeqSpec - laws - identityBoth has taken more than 1 m to execute. If this is not expected, consider using TestAspect.timeout to timeout runaway tests for faster diagnostics.
[1504](https://github.com/zio/zio-prelude/actions/runs/4340205509/jobs/7578530671#step:10:1505)
Test parSeqSpec - laws - identityFlatten has taken more than 1 m to execute. If this is not expected, consider using TestAspect.timeout to timeout runaway tests for faster diagnostics.
[1505](https://github.com/zio/zio-prelude/actions/runs/4340205509/jobs/7578530671#step:10:1506)
Test parSeqSpec - both - associative has taken more than 1 m to execute. If this is not expected, consider using TestAspect.timeout to timeout runaway tests for faster diagnostics.
[1506](https://github.com/zio/zio-prelude/actions/runs/4340205509/jobs/7578530671#step:10:1507)
Test parSeqSpec - both - commutative has taken more than 1 m to execute. If this is not expected, consider using TestAspect.timeout to timeout runaway tests for faster diagnostics.
[1507](https://github.com/zio/zio-prelude/actions/runs/4340205509/jobs/7578530671#step:10:1508)
Test parSeqSpec - both - identity has taken more than 1 m to execute. If this is not expected, consider using TestAspect.timeout to timeout runaway tests for faster diagnostics.
[1508](https://github.com/zio/zio-prelude/actions/runs/4340205509/jobs/7578530671#step:10:1509)
Test parSeqSpec - then - associative has taken more than 1 m to execute. If this is not expected, consider using TestAspect.timeout to timeout runaway tests for faster diagnostics.
[1509](https://github.com/zio/zio-prelude/actions/runs/4340205509/jobs/7578530671#step:10:1510)
Test parSeqSpec - then - commutative has taken more than 1 m to execute. If this is not expected, consider using TestAspect.timeout to timeout runaway tests for faster diagnostics.
[1510](https://github.com/zio/zio-prelude/actions/runs/4340205509/jobs/7578530671#step:10:1511)
Test parSeqSpec - then - identity has taken more than 1 m to execute. If this is not expected, consider using TestAspect.timeout to timeout runaway tests for faster diagnostics.
[1511](https://github.com/zio/zio-prelude/actions/runs/4340205509/jobs/7578530671#step:10:1512)
```

while on your PR only this corresponding one is reported slow:
```scala
Test parSeqSpec - laws - forEach has taken more than 1 m to execute. If this is not expected, consider using TestAspect.timeout to timeout runaway tests for faster diagnostics.
[1679](https://github.com/zio/zio-prelude/actions/runs/4340205509/jobs/7578530671#step:10:1680)
```

**Comment by adamgfraser** [comment]
I think this is just nondeterminism.

**Comment by guizmaii** [comment]
Probably.

About:
> Let's leave the CI settings as is, get this in, and we can address the test timing separately.

I'm not sure to understand, sorry. Do you want me to change to 60?

**Comment by adamgfraser** [comment]
Yes please! 🙏

**Comment by guizmaii** [comment]
Done!

**Review by adamgfraser — APPROVED** [review]

**Review by mschuwalow — APPROVED** [review]

**Pull request merged**
