### PR TITLE
Ability to define custom `Assertion`s via test-functions

### LINKED ISSUE #1065: Ability to define custom `Assertion`s
Currently the list of assertions is quite limited and since `Assertion` trait is sealed users cant define new assertion. For example, if user wants to define assertion to test that a string is blank (does not contain only space-chars), the only way to do that is to use regular expressions. Although there is a simpler way: just reuse `String.isBlank` function to do that, something like:

```scala
val isBlank: Assertion[String] =
  Assertion.fromFunction("isBlank")(_.isBlank)
```

If we want to ensure that a list contains some element, we could write something like:

```scala
def containsElem[A](elem: A): Assertion[List[A]] =
  Assertion.fromFunction(s"containsElem($elem)")(_.contains(elem))
```

For the record, `Assertion` from `zio-test` has similar ability to define custom assertions from user-supplied functions.

### PR DESCRIPTION
**Pull request by nartamonov**
Fixes #1065

### CODE REVIEW

**Review by sideeffffect — CHANGES_REQUESTED** [review]
Thank you, looks really nice. But the code doesn't pass our build.
Run `sbt fix` to format your code and Scaladoc has issues with your new doc comment:
```
[error] /home/runner/work/zio-prelude/zio-prelude/macros/shared/src/main/scala/zio/prelude/Assertion.scala:57:49: Variable elem undefined in comment for method fromFunction in object Assertion
[error]    *     Assertion.fromFunction(s"containsElem($elem)")(_.contains(elem))
```

**Comment by nartamonov** [comment]
@sideeffffect Thank you, fixed!

**Comment by nartamonov** [comment]
Oopps. It seems it's not so easy as I thought because of macro limitations:

```
[error]  Newtype Assertion Failed
[error] You have defined your Assertion in a way that cannot be read at compile-time.
[error] Due to the limitations of macros, assertions cannot be abstracted into other definitions.
[error]
[error] Make certain your definition looks something like this:
[error]
[error]       import zio.prelude.Assertion._
[error]       override def assertion = assert(greaterThan(40) && lessThan(80))
[error]
[error]     NonBlankString("abc")
```

I'll try to find another way...

**Comment by adamgfraser** [comment]
Isn't this already done in #793?

**Comment by nartamonov** [comment]
@adamgfraser Oh, thank you, `assertCustom` (as implemented in #793) is exactly what I need, didn't discover it in codebase somehow :-) Happy to close this PR.

**Pull request closed without merging**
